# NOTE: The schema is optional, as it defaults to the file type's official schema
# schema = "https://raw.githubusercontent.com/Outer-Wilds-New-Horizons/new-horizons/main/NewHorizons/Schemas/dialogue_schema.xsd"
file_type = "DialogueTree"
name_field = "Ernesto"

[[dialogue_node]]
name = "START"
entry_condition = "DEFAULT"

[[dialogue_node.dialogue]]
page = ["Hey it's me Ernesto the magic talking anglerfish."]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Wow you can talk?"
dialogue_target = "1"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "What do you think about Geswaldo?"
dialogue_target = "2"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Where did you guys come from?"
dialogue_target = "3"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "I'll see you later."
dialogue_target = "4"

[[dialogue_node.reveal_facts]]
fact_id = [
  "EXAMPLES_ERNESTO"
]

[[dialogue_node]]
name = "1"

[[dialogue_node.dialogue]]
page = [
  "No I can't, you must be mistaken.",
  "Haha that's a joke. I took speaking as an elective in college."
]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Oh."
dialogue_target = "START"

[[dialogue_node]]
name = "2"

[[dialogue_node.dialogue]]
page = [
  "I love him. He is my husband."
]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "That's beautiful. I'm so happy for both of you."
dialogue_target = "START"

[[dialogue_node]]
name = "3"

[[dialogue_node.dialogue]]
page = [
  "Geswaldo and I were visiting my cousin on Wetrock, I don't know about the other two. I don't know those guys."
]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Thanks for the info."
dialogue_target = "START"

[[dialogue_node.reveal_facts]]
fact_id = [
  "EXAMPLES_ERNESTO_COUSIN_RUMOR"
]

[[dialogue_node]]
name = "4"

[[dialogue_node.dialogue]]
page = ["Bye bye."]
