# NOTE: The schema is optional, as it defaults to the file type's official schema
# schema = "https://raw.githubusercontent.com/Outer-Wilds-New-Horizons/new-horizons/refs/heads/main/NewHorizons/Schemas/text_schema.xsd"
file_type = "NomaiObject"

[[text_block]]
id = 1
text = "this is an example"
location = ["A", "B"]

[[log_condition]]
location = ["A"]

[[log_condition.reveal_fact]]
id = "goobert"
condition = [1, 2]
